name: Pipeline de Integração Contínua (CI)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node de ambiente no GitHub
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Executar os Testes Unitários nativos
      run: node teste.js
      